development:
  adapter: postgresql
  encoding: unicode
  database: gee_fu_development
  pool: 5
  username: gee_fu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gee_fu_test
  pool: 5
  username: gee_fu
  password:

cucumber:
  adapter: postgresql
  encoding: unicode
  database: gee_fu_test
  pool: 5
  username: gee_fu
  password:
