#!/usr/bin/env ruby
#require 'thread'
#require File.expand_path('../../config/boot',  __FILE__)
#require 'commands/server'

#!/usr/bin/env ruby
require_relative '../config/boot'
require 'commands/server'
